=== yu-iskw/dbt-artifacts-parser-ts/packages/dbt-artifacts-parser/resources/catalog/catalog_v1.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "title": "CatalogArtifact",
  "properties": {
    "metadata": {
      "type": "object",
      "title": "CatalogMetadata",
      "properties": {
        "dbt_schema_version": {
          "type": "string"
        },
        "dbt_version": {
          "type": "string",
          "default": "1.11.6"
        },
        "generated_at": {
          "type": "string"
        },
        "invocation_id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "invocation_started_at": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "env": {
          "type": "object",
          "additionalProperties": {
            "type": "string"
          },
          "propertyNames": {
            "type": "string"
          }
        }
      },
      "additionalProperties": false
    },
    "nodes": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "title": "CatalogTable",
        "properties": {
          "metadata": {
            "type": "object",
            "title": "TableMetadata",
            "properties": {
              "type": {
                "type": "string"
              },
              "schema": {
                "type": "string"
              },
              "name": {
                "type": "string"
              },
              "database": {
                "anyOf": [
                  {
                    "type": "string"
                  },
                  {
                    "type": "null"
                  }
                ],
                "default": null
              },
              "comment": {
                "anyOf": [
                  {
                    "type": "string"
                  },
                  {
                    "type": "null"
                  }
                ],
                "default": null
              },
              "owner": {
                "anyOf": [
                  {
                    "type": "string"
                  },
                  {
                    "type": "null"
                  }
                ],
                "default": null
              }
            },
            "additionalProperties": false,
            "required": ["type", "schema", "name"]
          },
          "columns": {
            "type": "object",
            "additionalProperties": {
              "type": "object",
              "title": "ColumnMetadata",
              "properties": {
                "type": {
                  "type": "string"
                },
                "index": {
                  "type": "integer"
                },
                "name": {
                  "type": "string"
                },
                "comment": {
                  "anyOf": [
                    {
                      "type": "string"
                    },
                    {
                      "type": "null"
                    }
                  ],
                  "default": null
                }
              },
              "additionalProperties": false,
              "required": ["type", "index", "name"]
            },
            "propertyNames": {
              "type": "string"
            }
          },
          "stats": {
            "type": "object",
            "additionalProperties": {
              "type": "object",
              "title": "StatsItem",
              "properties": {
                "id": {
                  "type": "string"
                },
                "label": {
                  "type": "string"
                },
                "value": {
                  "anyOf": [
                    {
                      "type": "boolean"
                    },
                    {
                      "type": "string"
                    },
                    {
                      "type": "number"
                    },
                    {
                      "type": "null"
                    }
                  ]
                },
                "include": {
                  "type": "boolean"
                },
                "description": {
                  "anyOf": [
                    {
                      "type": "string"
                    },
                    {
                      "type": "null"
                    }
                  ],
                  "default": null
                }
              },
              "additionalProperties": false,
              "required": ["id", "label", "value", "include"]
            },
            "propertyNames": {
              "type": "string"
            }
          },
          "unique_id": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null
          }
        },
        "additionalProperties": false,
        "required": ["metadata", "columns", "stats"]
      },
      "propertyNames": {
        "type": "string"
      }
    },
    "sources": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "title": "CatalogTable",
        "properties": {
          "metadata": {
            "type": "object",
            "title": "TableMetadata",
            "properties": {
              "type": {
                "type": "string"
              },
              "schema": {
                "type": "string"
              },
              "name": {
                "type": "string"
              },
              "database": {
                "anyOf": [
                  {
                    "type": "string"
                  },
                  {
                    "type": "null"
                  }
                ],
                "default": null
              },
              "comment": {
                "anyOf": [
                  {
                    "type": "string"
                  },
                  {
                    "type": "null"
                  }
                ],
                "default": null
              },
              "owner": {
                "anyOf": [
                  {
                    "type": "string"
                  },
                  {
                    "type": "null"
                  }
                ],
                "default": null
              }
            },
            "additionalProperties": false,
            "required": ["type", "schema", "name"]
          },
          "columns": {
            "type": "object",
            "additionalProperties": {
              "type": "object",
              "title": "ColumnMetadata",
              "properties": {
                "type": {
                  "type": "string"
                },
                "index": {
                  "type": "integer"
                },
                "name": {
                  "type": "string"
                },
                "comment": {
                  "anyOf": [
                    {
                      "type": "string"
                    },
                    {
                      "type": "null"
                    }
                  ],
                  "default": null
                }
              },
              "additionalProperties": false,
              "required": ["type", "index", "name"]
            },
            "propertyNames": {
              "type": "string"
            }
          },
          "stats": {
            "type": "object",
            "additionalProperties": {
              "type": "object",
              "title": "StatsItem",
              "properties": {
                "id": {
                  "type": "string"
                },
                "label": {
                  "type": "string"
                },
                "value": {
                  "anyOf": [
                    {
                      "type": "boolean"
                    },
                    {
                      "type": "string"
                    },
                    {
                      "type": "number"
                    },
                    {
                      "type": "null"
                    }
                  ]
                },
                "include": {
                  "type": "boolean"
                },
                "description": {
                  "anyOf": [
                    {
                      "type": "string"
                    },
                    {
                      "type": "null"
                    }
                  ],
                  "default": null
                }
              },
              "additionalProperties": false,
              "required": ["id", "label", "value", "include"]
            },
            "propertyNames": {
              "type": "string"
            }
          },
          "unique_id": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null
          }
        },
        "additionalProperties": false,
        "required": ["metadata", "columns", "stats"]
      },
      "propertyNames": {
        "type": "string"
      }
    },
    "errors": {
      "anyOf": [
        {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        {
          "type": "null"
        }
      ],
      "default": null
    },
    "_compile_results": {
      "anyOf": [
        {},
        {
          "type": "null"
        }
      ],
      "default": null
    }
  },
  "additionalProperties": false,
  "required": ["metadata", "nodes", "sources"],
  "$id": "https://schemas.getdbt.com/dbt/catalog/v1.json"
}

=== yu-iskw/dbt-artifacts-parser-ts/packages/dbt-artifacts-parser/resources/catalog/v1/jaffle_shop/catalog_v2.json
{
  "metadata": {
    "dbt_schema_version": "https://schemas.getdbt.com/dbt/catalog/v1.json",
    "dbt_version": "2.0.6",
    "generated_at": "2026-09-24T04:48:09.991866Z",
    "invocation_id": "01a0d1be-0ee3-78d1-8fba-104682200313",
    "env": {}
  },
  "nodes": {
    "model.jaffle_shop.stg_customers": {
      "metadata": {
        "type": "BASE TABLE",
        "schema": "main",
        "name": "stg_customers",
        "database": "jaffle",
        "comment": null,
        "owner": ""
      },
      "columns": {
        "customer_id": {
          "type": "INTEGER",
          "index": 1,
          "name": "customer_id",
          "comment": null
        },
        "first_name": {
          "type": "VARCHAR",
          "index": 2,
          "name": "first_name",
          "comment": null
        }
      },
      "stats": {
        "has_stats": {
          "id": "has_stats",
          "label": "Has Stats?",
          "value": false,
          "include": false,
          "description": "Indicates whether there are statistics for this table"
        }
      },
      "unique_id": "model.jaffle_shop.stg_customers"
    }
  },
  "sources": {},
  "errors": null
}
