=== yu-iskw/dbt-artifacts-parser-ts/packages/dbt-artifacts-parser/resources/json-schema/run-results/run_results_v6.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "title": "RunResultsArtifact",
  "properties": {
    "metadata": {
      "type": "object",
      "title": "BaseArtifactMetadata",
      "properties": {
        "dbt_schema_version": {
          "type": "string"
        },
        "dbt_version": {
          "type": "string",
          "default": "1.12.0b1"
        },
        "generated_at": {
          "type": "string"
        },
        "invocation_id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "invocation_started_at": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "env": {
          "type": "object",
          "additionalProperties": {
            "type": "string"
          },
          "propertyNames": {
            "type": "string"
          }
        }
      },
      "additionalProperties": false,
      "required": ["dbt_schema_version"]
    },
    "results": {
      "type": "array",
      "items": {
        "type": "object",
        "title": "RunResultOutput",
        "properties": {
          "status": {
            "anyOf": [
              {
                "enum": [
                  "success",
                  "error",
                  "skipped",
                  "partial success",
                  "no-op",
                  "reused"
                ]
              },
              {
                "enum": ["pass", "error", "fail", "warn", "skipped"]
              },
              {
                "enum": ["pass", "warn", "error", "runtime error"]
              }
            ]
          },
          "timing": {
            "type": "array",
            "items": {
              "type": "object",
              "title": "TimingInfo",
              "properties": {
                "name": {
                  "type": "string"
                },
                "started_at": {
                  "anyOf": [
                    {
                      "type": "string"
                    },
                    {
                      "type": "null"
                    }
                  ],
                  "default": null
                },
                "completed_at": {
                  "anyOf": [
                    {
                      "type": "string"
                    },
                    {
                      "type": "null"
                    }
                  ],
                  "default": null
                }
              },
              "additionalProperties": false,
              "required": ["name"]
            }
          },
          "thread_id": {
            "type": "string"
          },
          "execution_time": {
            "type": "number"
          },
          "adapter_response": {
            "type": "object",
            "propertyNames": {
              "type": "string"
            }
          },
          "message": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "failures": {
            "anyOf": [
              {
                "type": "integer"
              },
              {
                "type": "null"
              }
            ]
          },
          "unique_id": {
            "type": "string"
          },
          "compiled": {
            "anyOf": [
              {
                "type": "boolean"
              },
              {
                "type": "null"
              }
            ]
          },
          "compiled_code": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "relation_name": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "batch_results": {
            "anyOf": [
              {
                "type": "object",
                "title": "BatchResults",
                "properties": {
                  "successful": {
                    "type": "array",
                    "items": {
                      "type": "array",
                      "prefixItems": [
                        {
                          "type": "string"
                        },
                        {
                          "type": "string"
                        }
                      ],
                      "maxItems": 2,
                      "minItems": 2
                    }
                  },
                  "failed": {
                    "type": "array",
                    "items": {
                      "type": "array",
                      "prefixItems": [
                        {
                          "type": "string"
                        },
                        {
                          "type": "string"
                        }
                      ],
                      "maxItems": 2,
                      "minItems": 2
                    }
                  }
                },
                "additionalProperties": false
              },
              {
                "type": "null"
              }
            ],
            "default": null
          },
          "overload_results": {
            "anyOf": [
              {
                "type": "object",
                "title": "OverloadResults",
                "properties": {
                  "successful": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  },
                  "failed": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  }
                },
                "additionalProperties": false
              },
              {
                "type": "null"
              }
            ],
            "default": null
          }
        },
        "additionalProperties": false,
        "required": [
          "status",
          "timing",
          "thread_id",
          "execution_time",
          "adapter_response",
          "message",
          "failures",
          "unique_id",
          "compiled",
          "compiled_code",
          "relation_name"
        ]
      }
    },
    "elapsed_time": {
      "type": "number"
    },
    "args": {
      "type": "object",
      "propertyNames": {
        "type": "string"
      }
    }
  },
  "additionalProperties": false,
  "required": ["metadata", "results", "elapsed_time"],
  "$id": "https://schemas.getdbt.com/dbt/run-results/v6.json"
}

=== yu-iskw/dbt-artifacts-parser-ts/packages/dbt-artifacts-parser/resources/run_results/v6/jaffle_shop/run_results_v2.json
{"metadata":{"dbt_schema_version":"https://schemas.getdbt.com/dbt/run-results/v6.json","dbt_version":"2.0.6","generated_at":"2026-09-24T04:48:09.482422Z","invocation_id":"01a0d1be-0ee3-78d1-8fba-104682200313","env":{}},"results":[{"status":"success","timing":[{"name":"compile","started_at":"2026-09-24T04:48:09.442435Z","completed_at":"2026-09-24T04:48:09.481214Z"},{"name":"execute","started_at":"2026-09-24T04:48:09.442435Z","completed_at":"2026-09-24T04:48:09.481214Z"}],"thread_id":"Thread-1 (worker)","execution_time":0.038779,"adapter_response":{"_message":"SUCCESS 0","code":"SUCCESS","message":"SUCCESS 0","rows_affected":0},"message":"Succeeded","failures":null,"unique_id":"model.jaffle_shop.stg_customers","compiled":null,"compiled_code":"select 1 as customer_id, 'Alice' as first_name","relation_name":"\"jaffle\".\"main\".\"stg_customers\"","batch_results":null}],"elapsed_time":0.038779,"args":{"command":"run","which":"run","full_refresh":false,"static_analysis":null}}
